arm:
  kinematics_solver: tiago_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

# ATTENZIONE: questo è un file fasullo messo come prova -- verrà sostituito con quello fatto bene 

